name: Build package

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x']

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Clean Solution
        run: dotnet clean
      - name: Install dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build --no-restore --output ${{ github.workspace }}/package
      - name: Run unit tests  
        run: dotnet test --logger trx --output ${{ github.workspace }}/package
      - name: Create the package
        run: dotnet pack -c Release ${{ github.workspace }}/Core.Cloud.Services.TransactionService.Functions/Core.Cloud.Services.TransactionService.Functions.*proj
      - uses: actions/upload-artifact@v1
        name: 'Upload build package'
        with:
          name: Build package
          path: ${{ github.workspace }}/package
