name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x']

    steps:
      - name: Checkout branch
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Clean Solution
        run: dotnet clean
      - name: Install dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build --no-restore --output ${{ github.workspace }}/package
      - name: Package build output
        run: dotnet pack --no-build --no-restore --output ${{ github.workspace }}/package
      - uses: actions/upload-artifact@v1
        name: 'Upload package'
        with:
          name: upload build package
          path: ${{ github.workspace }}/package
